# Extend the core String class.
class String

  # Convert this String to an identifier. This is a stable operation, so
  # anything that accept a name will also accept an identifier as well.
  def to_id
    return self.strip.gsub(/[^a-zA-Z0-9]+/, "-").downcase
  end

  # {{{ Clean HTML

  # Clean HTML generated by markup formatters. Such HTML tends to have extra
  # empty lines for no apparent reason. Cleaning it up seems to be safe enough,
  # and eliminates the ugly additional vertical space in the final HTML.
  def clean_markup_html
    return gsub("\r\n", "\n") \
          .gsub(/\n*<p>\n*/, "\n<p>\n") \
          .gsub(/\n*<\/p>\n*/, "\n</p>\n") \
          .gsub(/\n*<pre>\n+/, "\n<pre>\n") \
          .gsub(/\n+<\/pre>\n*/, "\n</pre>\n") \
          .sub(/^\n*/, "")
  end

  # }}}

end
