#!/bin/sh
true \
&& git add . \
&& rake clobber \
&& rake verify \
&& git commit "$@" \
&& tools/codnar-version > lib/codnar/version.rb \
&& git add lib/codnar/version.rb \
&& tools/codnar-changelog > ChangeLog \
&& git add ChangeLog \
&& rake all \
&& git commit --amend
