#!/usr/bin/ruby
 
subjects_by_id = {}
sorted_ids = []
 
log_lines = `git log --pretty='format:%ci::%an <%ae>::%s'`

log_lines.each do |log_line|
  date, author, subject = log_line.chomp.split("::")
  date, time, zone = date.split(" ")
  id = "#{date}\t#{author}"
  sorted_ids << id
  subjects_by_id[id] ||= []
  subjects_by_id[id] << subject
end
 
sorted_ids.uniq.each do |id|
  subjects = subjects_by_id[id]
  puts "#{id}\n\n"
  puts subjects.map { |subject| "\t* #{subject}" }.join("\n")
  puts "\n"
end
